### PR TITLE
Add onAuthFail event hook

### PR DESCRIPTION
**Pull request by a1gemmel**
Hi, here's my implementation for #42!

It lets the user register any number of callbacks to run when authentications fails, as well as exposing a `hasAuthFailed()` method. I'm still on the fence about the `hasAuthFailed` name, I prefer it to `didAuthFail` because that name suggests that we can determine that authentication succeeded.  

I chose the design of having the onAuthFail events only fire when authentication fails, and not on subsequent calls to `load()`, but I'm opening to changing that if you disagree.

### CODE REVIEW

**Comment by davidkudera** [comment]
Hi and thank you :+1:

**Comment by davidkudera** [comment]
About the `hasAuthFail`, right now it seems that it returns `true` if we have some `onAuthFail` callbacks attached, correct?

Shoudn't it rather check if the actual authentication failed?

Otherwise it looks really good

**Comment by a1gemmel** [comment]
You're right, that was a mistake. I've moved the 'authHasFailed = true;` line to inside the callback for gm_authFailure, and added a test to cover that case ;)

**Comment by davidkudera** [comment]
Hello, thanks for your PR and sorry for the long human-timeout. I rewrote this package to typescript with await/async support.

And based on your PR I added the onfailerror callback. You can try it with version 4.1.1. Thanks again

**Pull request closed without merging**
